while True:
    iso=input("Please input a word.\n").lower()
    a=(iso.count("a"))
    b=(iso.count("b"))
    c=(iso.count("c"))
    d=(iso.count("d"))
    e=(iso.count("e"))
    f=(iso.count("f"))
    g=(iso.count("g"))
    h=(iso.count("h"))
    i=(iso.count("i"))
    j=(iso.count("j"))
    k=(iso.count("k"))
    l=(iso.count("l"))
    m=(iso.count("m"))
    n=(iso.count("n"))
    o=(iso.count("o"))
    p=(iso.count("p"))
    q=(iso.count("q"))
    r=(iso.count("r"))
    s=(iso.count("s"))
    t=(iso.count("t"))
    u=(iso.count("u"))
    v=(iso.count("v"))
    w=(iso.count("w"))
    x=(iso.count("x"))
    y=(iso.count("y"))
    z=(iso.count("z"))
    if a<=1 and b<=1 and c<=1 and d<=1 and e<=1 and f<=1 and h<=1 and i<=1 and j<=1 and k<=1 and l<=1 and m<=1 and n<=1 and o<=1 and p<=1 and q<=1 and r<=1 and s<=1 and t<=1 and u<=1 and v<=1 and w<=1 and x<=1 and y<=1 and z<=1:
        print("That is an isogram")
    else:
        print("that is not an isogram")
